
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "controlnode"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder "C:/Users/Victor/lab-devops/ansible_lab/control_node", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
end
